//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace L1GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("L1GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;title&gt;AUTORIZACIÓN DE VENTA NO EXCLUSIVA&lt;/title&gt;
        ///  &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&quot;font-family: Arial; font-size: 11pt; text-align: justify; margin: 40px;&quot;&gt;
        ///
        ///  &lt;!-- Encabezado --&gt;
        ///  &lt;div style=&quot;font-size: 9pt; text-align: center; margin-bottom: 20px;&quot;&gt;
        ///    Mendoza 4407 | Costa Azul | Partido de la Costa&lt;br /&gt;
        ///    WhatsApp: +54 9 2257 511197 | www.costoyapropiedades.com.ar&lt;br /&gt;
        ///    &lt;b&gt;COSTOYA OSC [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string AUTORIZACION_VENTA {
            get {
                return ResourceManager.GetString("AUTORIZACION VENTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Online HTML Editor&lt;/title&gt;
        ///    &lt;style&gt;
        ///        table.border {
        ///            border-collapse: collapse;
        ///        }
        ///
        ///        table.border th, table.border td {
        ///            padding: 5px;
        ///            border: 1px solid black;
        ///        }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;table border=&quot;1&quot; style=&quot;width:100%&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td style=&quot;width:20%&quot;&gt;
        ///                &lt;table style=&quot;width:100%&quot;&gt;
        ///                    &lt;tr&gt;&lt;td align=&quot;center&quot;&gt;&lt;/td&gt;&lt;/tr&gt;
        ///        [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string FACTURA_TASACION {
            get {
                return ResourceManager.GetString("FACTURA TASACION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a     &lt;!DOCTYPE html&gt;
        ///    &lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;title&gt;Online HTML Editor&lt;/title&gt;
        ///        &lt;style&gt;
        ///            table.border {
        ///                border-collapse: collapse;
        ///            }
        ///    
        ///            table.border th, table.border td {
        ///                padding: 5px;
        ///                border: 1px solid black;
        ///            }
        ///        &lt;/style&gt;
        ///    &lt;/head&gt;
        ///    &lt;body&gt;
        ///        &lt;table border=&quot;1&quot; style=&quot;width:100%&quot;&gt;
        ///            &lt;tr&gt;
        ///                &lt;td style=&quot;width:20%&quot;&gt;
        ///                    &lt;table sty [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string FACTURA_VENTA {
            get {
                return ResourceManager.GetString("FACTURA VENTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo_Costoya_Negro {
            get {
                object obj = ResourceManager.GetObject("Logo Costoya Negro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Propiedad_sin_imagen {
            get {
                object obj = ResourceManager.GetObject("Propiedad sin imagen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SIGI_50 {
            get {
                object obj = ResourceManager.GetObject("SIGI 50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SIGI_ICON {
            get {
                object obj = ResourceManager.GetObject("SIGI ICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sin_propiedades {
            get {
                object obj = ResourceManager.GetObject("Sin propiedades", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
